### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by telostia** [alexxbull/rpchat#15]
Hi, Im trying to test run this repo but i am missing those environment variables, i did try to create an .env and trying to load but i think i am missing PGOPTIONS. what did you put there? cheers

**Comment by alexxbull** [comment]
Hi,

Unfortunately, the server this project was hosted on has been deleted so I can't say definitively but I believe it was:

`PGOPTIONS="-c 'custom.admin_password=${RPCHAT_ADMIN_PASSWORD}'"`

Hopefully that works for you. By the way, I was planning on redeploying this sometime soon so I can take and share notes on the steps needed to build this project if you're interested.

**Comment by telostia** [comment]
Cool. I will try it

**Comment by telostia** [comment]
seems like it's working :D

**Comment by telostia** [comment]
actually. there is a problem with the init.sql.. 

error:

postgres_social | 2023-08-12 07:50:38.407 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_social | 2023-08-12 07:50:38.437 UTC [21] LOG:  database system was interrupted; last known up at 2023-08-12 07:36:32 UTC
grpchat-server | !exclude db-data
grpchat-server | watching docker
postgres_social | 2023-08-12 07:50:38.513 UTC [21] LOG:  database system was not properly shut down; automatic recovery in progress
postgres_social | 2023-08-12 07:50:38.518 UTC [21] LOG:  redo starts at 0/164DC98
postgres_social | 2023-08-12 07:50:38.519 UTC [21] LOG:  invalid record length at 0/164DCD0: wanted 24, got 0

**Comment by telostia** [comment]
Hm... i stil cant get init.sql to work properly upon the creation of the postgres docker.

i get: 

```
2023-08-12 08:11:31.451 UTC [46] FATAL:  invalid command-line argument for server process: "-c
postgres_social | 2023-08-12 08:11:31.451 UTC [46] HINT:  Try "postgres --help" for more information.
postgres_social | psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  invalid command-line argument for server process: "-c
postgres_social | HINT:  Try "postgres --help" for more information.

any ideas?
```

**Comment by alexxbull** [comment]
I originally made and tested with Postgres 12 so I would try that version. I updated the docker-compose.yml to pull that image instead of the latest postgres.

**Comment by telostia** [comment]
I actually tested postgres-12-alpine before this though. i had the same issue so i switched back hoping it would fix it but to no avail.

**Comment by telostia** [comment]
ok the problem lies in the pgoptions not working... so i went and hardcode the admin password into the init.sql itself and it just works! this isn't ideal... but at least I got some lead where the problem lies now lol. thanks for your help. i'll look around and learn more about this messaging tech. also, the repo looks great, will try to learn something from it :)
